import { sortBy, uniqBy } from "es-toolkit/array";
import { packageListFile } from "../storage/mainPackageList";
import type { RnDep } from "../utils/types";

// `name` empty means the module uses `export = ConfigPlugin<...>` (see `checkValidity`'s bare
// module retry) - the whole module type IS the plugin, so there's no property to index into.
const line = (pkgName: string, importPath: string, name: string) =>
    name ? `"${pkgName}": ConfigPluginOptions<typeof import("${importPath}")["${name}"]>;` : `"${pkgName}": ConfigPluginOptions<typeof import("${importPath}")>;`;
const linesUntyped = (pkgName: string) => ["// This Packages doesn't ship types for config plugin:", `"${pkgName}": ConfigPluginOptions<unknown>;`];

const emptyStrArr = (): string[] => [];

// Raw TS diagnostic messages embed package-specific paths (module specifier, absolute file path,
// suggested `@types/...` name), so two packages failing for the *same* underlying reason never
// produce an identical error string and can't be grouped in the `Errors:` summary below. Collapse
// each known diagnostic shape back to its category so packages failing identically group together,
// the same way the hand-written `"Package uses \`exports\`..."` message already does.
const normalizeTsError = (error: string): string => {
    if (
        /^Could not find a declaration file for module '.*'\. '.*' implicitly has an 'any' type\. {3}Try `npm i --save-dev @types\/.*` if it exists or add a new declaration \(\.d\.ts\) file containing `declare module '.*';`$/.test(
            error,
        )
    ) {
        return "Could not find a declaration file for module (implicitly has an 'any' type - no .d.ts shipped)";
    }
    if (/^Property '.*' does not exist on type 'typeof import\(.*\)'\.$/.test(error)) {
        return "Property does not exist on module's type (no matching export)";
    }
    if (/^Cannot find module '.*' or its corresponding type declarations\.$/.test(error)) {
        return "Cannot find module or its corresponding type declarations";
    }
    return error;
};

export const getConfigPluginTypeCode = async (): Promise<string> => {
    const packages = await packageListFile.load("withPluginAndTypes");
    const packageList = uniqBy(sortBy(packages, ["npmPkg"]), (pkg) => pkg.npmPkg);
    const out = {
        errors: new Map<string, string[]>(),
        lines: emptyStrArr(),
        untypedPackages: emptyStrArr(),
    } satisfies Record<string, string[] | Map<string, string[]>>;

    const addError = (pkg: string, error: string) => {
        const packages = out.errors.get(error) || [];
        packages.push(pkg);
        out.errors.set(error, packages);
    };
    const addIgnoreLine = (types: RnDep["types"], npmPkg: string) => {
        const isIgnored = !!types?.override?.ignore || (!types?.valid && !types?.override?.path);
        if (types?.packageExport) {
            out.lines.push("// @ts-expect-error [Package uses `exports` in `package.json`, which breaks this import]");
            addError(npmPkg, "Package uses `exports` in `package.json`, which breaks this import");
        } else if (isIgnored) {
            out.lines.push("// @ts-expect-error [Invalid types or not exported]");
            out.untypedPackages.push(npmPkg);
        }
    };
    for (const { githubUrl, npmPkg, types } of packageList) {
        const override = types?.override ?? {};
        if (!npmPkg) {
            addError(githubUrl, "no npmPkg:");
            continue;
        }
        try {
            const path = override.path ?? types?.path;
            if (types?.path && override.path === types?.path) addError(npmPkg, "Redundant path override");
            if (types?.valid && override.ignore && !types.packageExport) addError(npmPkg, "Redundant ignore override");

            if ((!types?.override?.path && types?.error) || !path) {
                out.lines.push(...linesUntyped(npmPkg));
                addError(npmPkg, types?.error ? normalizeTsError(types.error) : "unknown Error");
            } else {
                const exportName = override.name ?? types?.exportName ?? "default";
                addIgnoreLine(types, npmPkg);
                out.lines.push(line(npmPkg, path, exportName));

                override.alias?.forEach((alias) => {
                    addIgnoreLine(types, npmPkg);
                    out.lines.push(line(alias, path, exportName));
                });
            }
        } catch (e) {
            const errorMessage = `${e instanceof Error ? e.message : String(e)}:`;
            addError(npmPkg, errorMessage);
        }
    }

    const template = `
import type { ConfigPluginOptions } from "./types";

// This file is auto-generated by the codegenCli

export interface ThirdPartyAutomatedPlugins {
    
    ${out.lines.join("\n    ")}
      
    /* Errors:
${JSON.stringify([...out.errors.entries()], null, 2)}
    */
}
`;

    return template;
};
