import type { ConfigPluginOptions } from "./types";

// This file is auto-generated by the codegenCli

export interface ThirdPartyAutomatedPlugins {
    "@adyen/react-native": ConfigPluginOptions<typeof import("@adyen/react-native/plugin/build/withAdyen")["default"]>;
    "@allboatsrise/expo-gigya": ConfigPluginOptions<typeof import("@allboatsrise/expo-gigya/plugin/build/index")["default"]>;
    "@allboatsrise/expo-marketingcloudsdk": ConfigPluginOptions<typeof import("@allboatsrise/expo-marketingcloudsdk/plugin/build/index")["default"]>;
    "@animo-id/indy-sdk-expo-plugin": ConfigPluginOptions<typeof import("@animo-id/indy-sdk-expo-plugin/build/withIndySdk")["default"]>;
    "@animo-id/react-native-ble-didcomm": ConfigPluginOptions<typeof import("@animo-id/react-native-ble-didcomm/build/plugin")["default"]>;
    "@appandflow/expo-camera-characteristics": ConfigPluginOptions<typeof import("@appandflow/expo-camera-characteristics/plugin/build/index")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "@appzung/expo-config-code-push": ConfigPluginOptions<typeof import("@appzung/expo-config-code-push/build/withReactNativeCodePush")["default"]>;
    "@archimedes4/expo-msal": ConfigPluginOptions<typeof import("@archimedes4/expo-msal/plugin/main/index")["default"]>;
    "@armanatz/expo-hms-location": ConfigPluginOptions<typeof import("@armanatz/expo-hms-location/build/withHMSLocation")["default"]>;
    "@azesmway/react-native-unity": ConfigPluginOptions<typeof import("@azesmway/react-native-unity/lib/typescript/plugin/src/index")["default"]>;
    // @ts-expect-error [Package uses `exports` in `package.json`, which breaks this import]
    "@b8safe/react-native-safe": ConfigPluginOptions<typeof import("@b8safe/react-native-safe/plugin/build/withB8Safe")["default"]>;
    "@bacons/apple-colors": ConfigPluginOptions<typeof import("@bacons/apple-colors/plugin/build/withAndroidColors")["default"]>;
    "@bacons/apple-targets": ConfigPluginOptions<typeof import("@bacons/apple-targets/build/config-plugin")["withTargetsDir"]>;
    "@bam.tech/react-native-batch": ConfigPluginOptions<typeof import("@bam.tech/react-native-batch/plugin/build/withReactNativeBatch")["default"]>;
    "@bam.tech/react-native-msal": ConfigPluginOptions<typeof import("@bam.tech/react-native-msal/plugin/build/withReactNativeMSAL")["default"]>;
    "@bam.tech/react-native-ssl-pinning": ConfigPluginOptions<typeof import("@bam.tech/react-native-ssl-pinning/build/withSSLPinningConfig")["default"]>;
    "@batch.com/react-native-plugin": ConfigPluginOptions<typeof import("@batch.com/react-native-plugin/plugin/build/withReactNativeBatch")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "@beyondidentity/bi-sdk-react-native": ConfigPluginOptions<typeof import("@beyondidentity/bi-sdk-react-native/app.plugin")["default"]>;
    "@bitdrift/react-native": ConfigPluginOptions<typeof import("@bitdrift/react-native/typescript/packages/react-native/src/plugin/withBitdrift.d.ts")["default"]>;
    "@bittingz/expo-widgets": ConfigPluginOptions<typeof import("@bittingz/expo-widgets/plugin/build/index")["default"]>;
    "@bpm-sekeh/expo-local-authentication": ConfigPluginOptions<typeof import("@bpm-sekeh/expo-local-authentication/plugin/build/withLocalAuthentication")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "@bravemobile/react-native-code-push": ConfigPluginOptions<typeof import("@bravemobile/react-native-code-push/expo/plugin/withCodePush")["default"]>;
    "@braze/expo-plugin": ConfigPluginOptions<typeof import("@braze/expo-plugin/build/withBraze")["default"]>;
    // @ts-expect-error [Package uses `exports` in `package.json`, which breaks this import]
    "@calljmp/react-native": ConfigPluginOptions<typeof import("@calljmp/react-native/lib/withCalljmp")["default"]>;
    "@charmy.tech/react-native-admost": ConfigPluginOptions<typeof import("@charmy.tech/react-native-admost/plugin/build/index")["default"]>;
    "@clevertap/clevertap-expo-plugin": ConfigPluginOptions<typeof import("@clevertap/clevertap-expo-plugin/build/src/withClevertap")["default"]>;
    "@config-plugins/react-native-adjust": ConfigPluginOptions<typeof import("@config-plugins/react-native-adjust/build/withReactNativeAdjust")["default"]>;
    "@config-plugins/react-native-blob-util": ConfigPluginOptions<typeof import("@config-plugins/react-native-blob-util/build/withReactNativeBlobUtil")["default"]>;
    "@config-plugins/react-native-branch": ConfigPluginOptions<typeof import("@config-plugins/react-native-branch/build/withBranch")["default"]>;
    "@config-plugins/react-native-callkeep": ConfigPluginOptions<typeof import("@config-plugins/react-native-callkeep/build/withCallkeep")["default"]>;
    "@config-plugins/react-native-pdf": ConfigPluginOptions<typeof import("@config-plugins/react-native-pdf/build/withPdf")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "@corasan/image-compressor": ConfigPluginOptions<typeof import("@corasan/image-compressor/app.plugin")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "@criipto/verify-expo": ConfigPluginOptions<typeof import("@criipto/verify-expo/app.plugin")["default"]>;
    "@crossmint/client-sdk-react-native-ui": ConfigPluginOptions<typeof import("@crossmint/client-sdk-react-native-ui/dist/plugin/withGooglePay")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "@daily-co/config-plugin-rn-daily-js": ConfigPluginOptions<typeof import("@daily-co/config-plugin-rn-daily-js/build/withDaily")["default"]>;
    // This Packages doesn't ship types for config plugin:
    "@datadog/mobile-react-native": ConfigPluginOptions<unknown>;
    // @ts-expect-error [Invalid types or not exported]
    "@davotisolutions/expo-localization-utils": ConfigPluginOptions<typeof import("@davotisolutions/expo-localization-utils/app.plugin")["default"]>;
    // @ts-expect-error [Package uses `exports` in `package.json`, which breaks this import]
    "@dbkable/react-native-speech-to-text": ConfigPluginOptions<typeof import("@dbkable/react-native-speech-to-text/app.plugin")["default"]>;
    // @ts-expect-error [Package uses `exports` in `package.json`, which breaks this import]
    "@deeplinknow/react-native": ConfigPluginOptions<typeof import("@deeplinknow/react-native/plugin/build/index")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "@didomi/react-native": ConfigPluginOptions<typeof import("@didomi/react-native/plugin/withDidomi")["default"]>;
    "@divvi/mobile": ConfigPluginOptions<typeof import("@divvi/mobile/plugin/build/index")["default"]>;
    "@embrace-io/react-native": ConfigPluginOptions<typeof import("@embrace-io/react-native/lib/src/plugin/index")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "@evennit/notifee-expo-plugin": ConfigPluginOptions<typeof import("@evennit/notifee-expo-plugin/dist/plugin/withNotifee")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "@faysalbsata/uaepass-auth": ConfigPluginOptions<typeof import("@faysalbsata/uaepass-auth/app.plugin")["default"]>;
    // @ts-expect-error [Package uses `exports` in `package.json`, which breaks this import]
    "@fingerprintjs/fingerprintjs-pro-react-native": ConfigPluginOptions<typeof import("@fingerprintjs/fingerprintjs-pro-react-native/plugin/dist/withFingerprint")["default"]>;
    "@fishjam-cloud/react-native-client": ConfigPluginOptions<typeof import("@fishjam-cloud/react-native-client/plugin/build/withFishjam")["default"]>;
    // This Packages doesn't ship types for config plugin:
    "@fleetbase/react-native-mapbox-navigation": ConfigPluginOptions<unknown>;
    "@getcello/cello-react-native": ConfigPluginOptions<typeof import("@getcello/cello-react-native/lib/typescript/src/expo-plugin/index")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "@giphy/react-native-sdk": ConfigPluginOptions<typeof import("@giphy/react-native-sdk/app.plugin")["default"]>;
    // @ts-expect-error [Package uses `exports` in `package.json`, which breaks this import]
    "@grupalia/react-native-photo-picker": ConfigPluginOptions<typeof import("@grupalia/react-native-photo-picker/app.plugin")["default"]>;
    "@heartbot/expo-google-authentication": ConfigPluginOptions<typeof import("@heartbot/expo-google-authentication/plugin/build/index")["default"]>;
    // @ts-expect-error [Package uses `exports` in `package.json`, which breaks this import]
    "@honeycombio/opentelemetry-react-native": ConfigPluginOptions<typeof import("@honeycombio/opentelemetry-react-native/lib/typescript/module/src/plugin/withUUIDIosPlugin")["default"]>;
    // @ts-expect-error [Package uses `exports` in `package.json`, which breaks this import]
    "@hot-updater/react-native": ConfigPluginOptions<typeof import("@hot-updater/react-native/plugin/build/withHotUpdater")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "@huddle01/react-native-call-detection": ConfigPluginOptions<typeof import("@huddle01/react-native-call-detection/expo/withCallDetector")["default"]>;
    // @ts-expect-error [Package uses `exports` in `package.json`, which breaks this import]
    "@huymobile/react-native-sms-retriever-nitro-module": ConfigPluginOptions<typeof import("@huymobile/react-native-sms-retriever-nitro-module/app.plugin")["default"]>;
    // @ts-expect-error [Package uses `exports` in `package.json`, which breaks this import]
    "@intercom/intercom-react-native": ConfigPluginOptions<typeof import("@intercom/intercom-react-native/lib/typescript/module/expo-plugins/index")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "@isudaji/react-native-install-apk": ConfigPluginOptions<typeof import("@isudaji/react-native-install-apk/index")["default"]>;
    "@iterable/expo-plugin": ConfigPluginOptions<typeof import("@iterable/expo-plugin/plugin/build/withIterable")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "@journeyapps/react-native-quick-sqlite": ConfigPluginOptions<typeof import("@journeyapps/react-native-quick-sqlite/lib/typescript/withUseFrameworks")["default"]>;
    "@jt-technologies/expo-idnow": ConfigPluginOptions<typeof import("@jt-technologies/expo-idnow/plugin/build/index")["default"]>;
    "@kickstartcrew/expo-financekit": ConfigPluginOptions<typeof import("@kickstartcrew/expo-financekit/build/plugin")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "@kingstinct/react-native-activity-kit": ConfigPluginOptions<typeof import("@kingstinct/react-native-activity-kit/app.plugin")["default"]>;
    // @ts-expect-error [Package uses `exports` in `package.json`, which breaks this import]
    "@kingstinct/react-native-healthkit": ConfigPluginOptions<typeof import("@kingstinct/react-native-healthkit/app.plugin")["default"]>;
    "@leanplum/react-native-sdk": ConfigPluginOptions<typeof import("@leanplum/react-native-sdk/plugin/build/withLeanplumSDK")["default"]>;
    // @ts-expect-error [Package uses `exports` in `package.json`, which breaks this import]
    "@lightbase/rn-design-system": ConfigPluginOptions<typeof import("@lightbase/rn-design-system/lib/typescript/module/src/expo")["default"]>;
    "@livekit/react-native-expo-plugin": ConfigPluginOptions<typeof import("@livekit/react-native-expo-plugin/plugin/build/index")["default"]>;
    "@lovesworking/watermelondb-expo-plugin-sdk-52-plus": ConfigPluginOptions<typeof import("@lovesworking/watermelondb-expo-plugin-sdk-52-plus/build/withWatermelon")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "@luciq/react-native": ConfigPluginOptions<typeof import("@luciq/react-native/plugin/build/index")["default"]>;
    "@lyrahealth-inc/react-native-orientation-plugin": ConfigPluginOptions<typeof import("@lyrahealth-inc/react-native-orientation-plugin/build/withOrientation")["default"]>;
    "@mankin/expo-mods-append-build-version-suffix": ConfigPluginOptions<typeof import("@mankin/expo-mods-append-build-version-suffix/build/withSuffix")["default"]>;
    "@mankin/expo-mods-ble": ConfigPluginOptions<typeof import("@mankin/expo-mods-ble/build/withBLE")["default"]>;
    "@mankin/expo-mods-jpush": ConfigPluginOptions<typeof import("@mankin/expo-mods-jpush/build/withJPush")["default"]>;
    "@mankin/expo-mods-localized-name": ConfigPluginOptions<typeof import("@mankin/expo-mods-localized-name/build/withLocalizedName")["default"]>;
    // @ts-expect-error [Package uses `exports` in `package.json`, which breaks this import]
    "@maplibre/maplibre-react-native": ConfigPluginOptions<typeof import("@maplibre/maplibre-react-native/lib/typescript/commonjs/src/plugin/withMapLibre")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "@mapsindoors/react-native-maps-indoors-google-maps": ConfigPluginOptions<typeof import("@mapsindoors/react-native-maps-indoors-google-maps/app.plugin")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "@mapsindoors/react-native-maps-indoors-mapbox": ConfigPluginOptions<typeof import("@mapsindoors/react-native-maps-indoors-mapbox/app.plugin")["default"]>;
    "@matthewwarnes/react-native-ble-manager-plugin": ConfigPluginOptions<typeof import("@matthewwarnes/react-native-ble-manager-plugin/build/withBLE")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "@mikekhristo/expo-tiktok-opensdk": ConfigPluginOptions<typeof import("@mikekhristo/expo-tiktok-opensdk/plugin/build/withTikTokOpenSDK")["default"]>;
    // @ts-expect-error [Package uses `exports` in `package.json`, which breaks this import]
    "@mj-studio/react-native-naver-map": ConfigPluginOptions<typeof import("@mj-studio/react-native-naver-map/expo-config-plugin/build/index")["default"]>;
    "@mobione/thermalib-expo": ConfigPluginOptions<typeof import("@mobione/thermalib-expo/plugin/build/index")["default"]>;
    "@morrowdigital/watermelondb-expo-plugin": ConfigPluginOptions<typeof import("@morrowdigital/watermelondb-expo-plugin/build/withWatermelon")["default"]>;
    "@mykin-ai/expo-audio-stream": ConfigPluginOptions<typeof import("@mykin-ai/expo-audio-stream/plugin/build/index")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "@native-ui-org/native-modules": ConfigPluginOptions<typeof import("@native-ui-org/native-modules/app.plugin")["default"]>;
    // @ts-expect-error [Package uses `exports` in `package.json`, which breaks this import]
    "@naveen521kk/react-native-tokenizer": ConfigPluginOptions<typeof import("@naveen521kk/react-native-tokenizer/app.plugin")["default"]>;
    "@niondigital/cleverpush-expo-config-plugin": ConfigPluginOptions<typeof import("@niondigital/cleverpush-expo-config-plugin/build/withCleverPush")["default"]>;
    "@niondigital/widgets-expo-config-plugin": ConfigPluginOptions<typeof import("@niondigital/widgets-expo-config-plugin/build/withWidgets")["default"]>;
    // @ts-expect-error [Package uses `exports` in `package.json`, which breaks this import]
    "@novastera-oss/rn-google-signin": ConfigPluginOptions<typeof import("@novastera-oss/rn-google-signin/expo-plugin/build/withGoogleSignIn")["default"]>;
    // @ts-expect-error [Package uses `exports` in `package.json`, which breaks this import]
    "@oleg_svetlichnyi/expo-icloud-storage": ConfigPluginOptions<typeof import("@oleg_svetlichnyi/expo-icloud-storage/app.plugin")["default"]>;
    // @ts-expect-error [Package uses `exports` in `package.json`, which breaks this import]
    "@opacity-labs/react-native-opacity": ConfigPluginOptions<typeof import("@opacity-labs/react-native-opacity/expo-plugin/build/index")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "@openreplay/react-native": ConfigPluginOptions<typeof import("@openreplay/react-native/app.plugin")["default"]>;
    "@peulda/expo-plugin-channel-io": ConfigPluginOptions<typeof import("@peulda/expo-plugin-channel-io/build/index")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "@poilabs-dev/analysis-sdk-plugin": ConfigPluginOptions<typeof import("@poilabs-dev/analysis-sdk-plugin/app.plugin")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "@poilabs-dev/navigation-sdk-plugin": ConfigPluginOptions<typeof import("@poilabs-dev/navigation-sdk-plugin/app.plugin")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "@poilabs-dev/vd-navigation-sdk-plugin": ConfigPluginOptions<typeof import("@poilabs-dev/vd-navigation-sdk-plugin/app.plugin")["default"]>;
    // @ts-expect-error [Package uses `exports` in `package.json`, which breaks this import]
    "@portone/react-native-sdk": ConfigPluginOptions<typeof import("@portone/react-native-sdk/lib/typescript/plugin")["default"]>;
    "@prisma/react-native": ConfigPluginOptions<typeof import("@prisma/react-native/plugin/build/index")["default"]>;
    "@react-native-ai/mlc": ConfigPluginOptions<typeof import("@react-native-ai/mlc/lib/typescript/expo-plugin")["default"]>;
    "@react-native-community/datetimepicker": ConfigPluginOptions<typeof import("@react-native-community/datetimepicker/plugin/build/withDateTimePickerStyles")["default"]>;
    "@react-native-firebase/app": ConfigPluginOptions<typeof import("@react-native-firebase/app/plugin/build/index")["default"]>;
    "@react-native-firebase/app-check": ConfigPluginOptions<typeof import("@react-native-firebase/app-check/plugin/build/index")["default"]>;
    "@react-native-firebase/app-distribution": ConfigPluginOptions<typeof import("@react-native-firebase/app-distribution/plugin/build/index")["default"]>;
    "@react-native-firebase/auth": ConfigPluginOptions<typeof import("@react-native-firebase/auth/plugin/build/index")["default"]>;
    "@react-native-firebase/crashlytics": ConfigPluginOptions<typeof import("@react-native-firebase/crashlytics/plugin/build/index")["default"]>;
    "@react-native-firebase/messaging": ConfigPluginOptions<typeof import("@react-native-firebase/messaging/plugin/build/index")["default"]>;
    "@react-native-firebase/perf": ConfigPluginOptions<typeof import("@react-native-firebase/perf/plugin/build/index")["default"]>;
    // @ts-expect-error [Package uses `exports` in `package.json`, which breaks this import]
    "@react-native-google-signin/google-signin": ConfigPluginOptions<typeof import("@react-native-google-signin/google-signin/plugin/build/withGoogleSignIn")["default"]>;
    "@react-native-kakao/core": ConfigPluginOptions<typeof import("@react-native-kakao/core/expo-config-plugin/build/index")["default"]>;
    "@react-native-seoul/kakao-login": ConfigPluginOptions<typeof import("@react-native-seoul/kakao-login/plugins/index")["default"]>;
    "@react-native-seoul/naver-login": ConfigPluginOptions<typeof import("@react-native-seoul/naver-login/plugin/build/index")["default"]>;
    "@react-native-tvos/config-tv": ConfigPluginOptions<typeof import("@react-native-tvos/config-tv/build/withTV")["default"]>;
    "@react-native-voice/voice": ConfigPluginOptions<typeof import("@react-native-voice/voice/plugin/build/withVoice")["default"]>;
    "@reactvision/react-viro": ConfigPluginOptions<typeof import("@reactvision/react-viro/dist/plugins/withViro")["default"]>;
    // @ts-expect-error [Package uses `exports` in `package.json`, which breaks this import]
    "@reclaimprotocol/inapp-rn-sdk": ConfigPluginOptions<typeof import("@reclaimprotocol/inapp-rn-sdk/expo-plugin/build/index")["default"]>;
    // @ts-expect-error [Package uses `exports` in `package.json`, which breaks this import]
    "@rnmapbox/maps": ConfigPluginOptions<typeof import("@rnmapbox/maps/plugin/build/withMapbox")["default"]>;
    "@rokt/react-native-sdk": ConfigPluginOptions<typeof import("@rokt/react-native-sdk/plugin/build/withRoktSDK")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "@rownd/react-native": ConfigPluginOptions<typeof import("@rownd/react-native/app.plugin")["default"]>;
    "@sd-tech/rn-camera-face-blur": ConfigPluginOptions<typeof import("@sd-tech/rn-camera-face-blur/lib/typescript/expo-plugin/withVisionCamera")["default"]>;
    "@sentry/react-native": ConfigPluginOptions<typeof import("@sentry/react-native/plugin/build/index")["default"]>;
    "@sentry/react-native/expo": ConfigPluginOptions<typeof import("@sentry/react-native/plugin/build/index")["default"]>;
    "@siteed/design-system": ConfigPluginOptions<typeof import("@siteed/design-system/dist/plugin/src/index")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "@siteed/expo-audio-studio": ConfigPluginOptions<typeof import("@siteed/expo-audio-studio/app.plugin")["default"]>;
    "@solana-mobile/mobile-wallet-adapter-expo-bottom-sheet": ConfigPluginOptions<typeof import("@solana-mobile/mobile-wallet-adapter-expo-bottom-sheet/plugin/build/withBottomSheet")["default"]>;
    // This Packages doesn't ship types for config plugin:
    "@sparkfabrik/react-native-idfa-aaid": ConfigPluginOptions<unknown>;
    // @ts-expect-error [Invalid types or not exported]
    "@spreen/ffmpeg-kit-react-native-config": ConfigPluginOptions<typeof import("@spreen/ffmpeg-kit-react-native-config/build/withFFMPEG")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "@stonega/expo-google-signin": ConfigPluginOptions<typeof import("@stonega/expo-google-signin/app.plugin")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "@stream-io/video-react-native-sdk": ConfigPluginOptions<typeof import("@stream-io/video-react-native-sdk/expo-config-plugin/dist/index")["default"]>;
    "@stripe/stripe-react-native": ConfigPluginOptions<typeof import("@stripe/stripe-react-native/lib/typescript/src/plugin/withStripe")["default"]>;
    "@stripe/stripe-terminal-react-native": ConfigPluginOptions<typeof import("@stripe/stripe-terminal-react-native/lib/typescript/src/plugin/withStripeTerminal")["default"]>;
    "@survicate/react-native-survicate": ConfigPluginOptions<typeof import("@survicate/react-native-survicate/lib/typescript/expo/withSurvicate")["default"]>;
    "@thedev132/expo-widgets": ConfigPluginOptions<typeof import("@thedev132/expo-widgets/plugin/build/index")["default"]>;
    "@threls/expo-pusher-beams": ConfigPluginOptions<typeof import("@threls/expo-pusher-beams/plugin/build/withPusherBeams")["default"]>;
    // @ts-expect-error [Package uses `exports` in `package.json`, which breaks this import]
    "@track-asia/trackasia-react-native": ConfigPluginOptions<typeof import("@track-asia/trackasia-react-native/lib/typescript/module/src/plugin/ios")["default"]>;
    // This Packages doesn't ship types for config plugin:
    "@tripleplaypay/react-native": ConfigPluginOptions<unknown>;
    // @ts-expect-error [Invalid types or not exported]
    "@tryvital/vital-core-react-native": ConfigPluginOptions<typeof import("@tryvital/vital-core-react-native/app.plugin")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "@tryvital/vital-health-react-native": ConfigPluginOptions<typeof import("@tryvital/vital-health-react-native/app.plugin")["default"]>;
    // @ts-expect-error [Package uses `exports` in `package.json`, which breaks this import]
    "@vietmap/vietmap-gl-react-native": ConfigPluginOptions<typeof import("@vietmap/vietmap-gl-react-native/plugin/build/withVietmap")["default"]>;
    "@vivition/expo-camera": ConfigPluginOptions<typeof import("@vivition/expo-camera/plugin/build/withCamera")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "@vonovak/react-native-theme-control": ConfigPluginOptions<typeof import("@vonovak/react-native-theme-control/plugin/build/withThemeControl")["default"]>;
    "@woosmap/expo-plugin-geofencing-batch": ConfigPluginOptions<typeof import("@woosmap/expo-plugin-geofencing-batch/build/index")["default"]>;
    "@wwdrew/expo-android-account-manager": ConfigPluginOptions<typeof import("@wwdrew/expo-android-account-manager/plugin/build/index")["default"]>;
    "@wwdrew/expo-spotify-sdk": ConfigPluginOptions<typeof import("@wwdrew/expo-spotify-sdk/plugin/build/index")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "@xmartlabs/react-native-line": ConfigPluginOptions<typeof import("@xmartlabs/react-native-line/plugin/withLineSDK")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "@youssefhenna/expo-enode-link-sdk": ConfigPluginOptions<typeof import("@youssefhenna/expo-enode-link-sdk/plugin/withCustomAppTheme")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "@youssefhenna/expo-mapbox-navigation": ConfigPluginOptions<typeof import("@youssefhenna/expo-mapbox-navigation/plugin/withIosConfig")["default"]>;
    // This Packages doesn't ship types for config plugin:
    "@yownes/core": ConfigPluginOptions<unknown>;
    "@zamplyy/react-native-vector-image-plugin": ConfigPluginOptions<typeof import("@zamplyy/react-native-vector-image-plugin/build/withVectorImage")["default"]>;
    "@zoontek/react-native-navigation-bar": ConfigPluginOptions<typeof import("@zoontek/react-native-navigation-bar/dist/typescript/expo")["default"]>;
    "airship-expo-plugin": ConfigPluginOptions<typeof import("airship-expo-plugin/plugin/build/withAirship")["default"]>;
    "android-glance-widget-expo": ConfigPluginOptions<typeof import("android-glance-widget-expo/plugin/build/index")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "app-icon-badge": ConfigPluginOptions<typeof import("app-icon-badge/dist/app.plugin")["default"]>;
    "apple-healthkit-export": ConfigPluginOptions<typeof import("apple-healthkit-export/plugin/build/index")["default"]>;
    "banuba-expo": ConfigPluginOptions<typeof import("banuba-expo/plugin/build/withBanuba")["default"]>;
    "bitmovin-player-react-native": ConfigPluginOptions<typeof import("bitmovin-player-react-native/plugin/build/index")["default"]>;
    "bitmovin-player-react-native-analytics-conviva": ConfigPluginOptions<typeof import("bitmovin-player-react-native-analytics-conviva/plugin/build/index")["default"]>;
    blueswarm: ConfigPluginOptions<typeof import("blueswarm/plugin/build/withBlueSwarm")["default"]>;
    "cleverpush-expo-plugin": ConfigPluginOptions<typeof import("cleverpush-expo-plugin/build/cleverpush/withCleverPush")["default"]>;
    // This Packages doesn't ship types for config plugin:
    customerapp: ConfigPluginOptions<unknown>;
    // @ts-expect-error [Invalid types or not exported]
    "dojah-kyc-sdk-react-expo": ConfigPluginOptions<typeof import("dojah-kyc-sdk-react-expo/app.plugin")["default"]>;
    // This Packages doesn't ship types for config plugin:
    eos: ConfigPluginOptions<unknown>;
    "expo-ads-facebook": ConfigPluginOptions<typeof import("expo-ads-facebook/plugin/build/withFacebookAds")["default"]>;
    "expo-alarm-module": ConfigPluginOptions<typeof import("expo-alarm-module/plugin/build/withExpoAlarmModule")["default"]>;
    "expo-alternate-app-icons": ConfigPluginOptions<typeof import("expo-alternate-app-icons/plugin/build/index")["default"]>;
    "expo-app-auth": ConfigPluginOptions<typeof import("expo-app-auth/plugin/build/withAppAuth")["default"]>;
    "expo-appcenter": ConfigPluginOptions<typeof import("expo-appcenter/plugin/build/index")["default"]>;
    "expo-apple-authentication": ConfigPluginOptions<typeof import("expo-apple-authentication/plugin/build/withAppleAuth")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "expo-applovin-ads": ConfigPluginOptions<typeof import("expo-applovin-ads/plugin/src/index")["default"]>;
    // @ts-expect-error [Package uses `exports` in `package.json`, which breaks this import]
    "expo-asset": ConfigPluginOptions<typeof import("expo-asset/plugin/build/withAssets")["default"]>;
    "expo-audio": ConfigPluginOptions<typeof import("expo-audio/plugin/build/withAudio")["default"]>;
    "expo-audio-studio": ConfigPluginOptions<typeof import("expo-audio-studio/plugin/build/withAudio")["default"]>;
    "expo-av": ConfigPluginOptions<typeof import("expo-av/plugin/build/withAV")["default"]>;
    "expo-background-fetch": ConfigPluginOptions<typeof import("expo-background-fetch/plugin/build/withBackgroundFetch")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "expo-background-recording": ConfigPluginOptions<typeof import("expo-background-recording/app.plugin")["default"]>;
    "expo-background-task": ConfigPluginOptions<typeof import("expo-background-task/plugin/build/withBackgroundTask")["default"]>;
    "expo-banuba": ConfigPluginOptions<typeof import("expo-banuba/plugin/build/withBanuba")["default"]>;
    "expo-barcode-scanner": ConfigPluginOptions<typeof import("expo-barcode-scanner/plugin/build/withBarcodeScanner")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "expo-bare-kit": ConfigPluginOptions<typeof import("expo-bare-kit/plugin/index")["default"]>;
    "expo-ble": ConfigPluginOptions<typeof import("expo-ble/plugin/build/index")["default"]>;
    "expo-branch": ConfigPluginOptions<typeof import("expo-branch/plugin/build/withBranch")["default"]>;
    "expo-brightness": ConfigPluginOptions<typeof import("expo-brightness/plugin/build/withBrightness")["default"]>;
    "expo-brother-printer-sdk": ConfigPluginOptions<typeof import("expo-brother-printer-sdk/plugin/build/index")["default"]>;
    "expo-build-flags": ConfigPluginOptions<typeof import("expo-build-flags/build/config-plugin/index")["default"]>;
    "expo-build-properties": ConfigPluginOptions<typeof import("expo-build-properties/build/withBuildProperties")["default"]>;
    "expo-calendar": ConfigPluginOptions<typeof import("expo-calendar/plugin/build/withCalendar")["default"]>;
    "expo-camera": ConfigPluginOptions<typeof import("expo-camera/plugin/build/withCamera")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "expo-cdnbye": ConfigPluginOptions<typeof import("expo-cdnbye/app.plugin")["default"]>;
    "expo-cellular": ConfigPluginOptions<typeof import("expo-cellular/plugin/build/withCellular")["default"]>;
    "expo-check-installed-apps": ConfigPluginOptions<typeof import("expo-check-installed-apps/plugin/build/index")["default"]>;
    // @ts-expect-error [Package uses `exports` in `package.json`, which breaks this import]
    "expo-clear-keychain": ConfigPluginOptions<typeof import("expo-clear-keychain/lib/typescript/module/src/index")["default"]>;
    "expo-color-space-plugin": ConfigPluginOptions<typeof import("expo-color-space-plugin/build/index")["default"]>;
    "expo-config-plugin-ios-share-extension": ConfigPluginOptions<typeof import("expo-config-plugin-ios-share-extension/build/index")["default"]>;
    "expo-contacts": ConfigPluginOptions<typeof import("expo-contacts/plugin/build/withContacts")["default"]>;
    "expo-core-spotlight": ConfigPluginOptions<typeof import("expo-core-spotlight/plugin/build/index")["default"]>;
    // This Packages doesn't ship types for config plugin:
    "expo-custom-android-styles-plugin": ConfigPluginOptions<unknown>;
    "expo-custom-assets": ConfigPluginOptions<typeof import("expo-custom-assets/build/index")["default"]>;
    "expo-datadog": ConfigPluginOptions<typeof import("expo-datadog/build/plugin/index")["default"]>;
    "expo-dev-client": ConfigPluginOptions<typeof import("expo-dev-client/plugin/build/withDevClient")["default"]>;
    // This Packages doesn't ship types for config plugin:
    "expo-dev-launcher": ConfigPluginOptions<unknown>;
    "expo-document-picker": ConfigPluginOptions<typeof import("expo-document-picker/plugin/build/withDocumentPicker")["default"]>;
    "expo-dynamic-app-icon": ConfigPluginOptions<typeof import("expo-dynamic-app-icon/plugin/build/withDynamicIcon")["default"]>;
    "expo-embed-android-unity-project": ConfigPluginOptions<typeof import("expo-embed-android-unity-project/build/index")["default"]>;
    "expo-facebook": ConfigPluginOptions<typeof import("expo-facebook/plugin/build/withFacebook")["default"]>;
    "expo-file-system": ConfigPluginOptions<typeof import("expo-file-system/plugin/build/withFileSystem")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "expo-firebase-app-distribution": ConfigPluginOptions<typeof import("expo-firebase-app-distribution/dist/index")["default"]>;
    "expo-firebase-core": ConfigPluginOptions<typeof import("expo-firebase-core/plugin/build/withFirebaseCore")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "expo-floating-bubble": ConfigPluginOptions<typeof import("expo-floating-bubble/app.plugin")["default"]>;
    // @ts-expect-error [Package uses `exports` in `package.json`, which breaks this import]
    "expo-font": ConfigPluginOptions<typeof import("expo-font/plugin/build/withFonts")["default"]>;
    "expo-google-sign-in": ConfigPluginOptions<typeof import("expo-google-sign-in/plugin/build/withGoogleSignIn")["default"]>;
    "expo-gradle-ext-vars": ConfigPluginOptions<typeof import("expo-gradle-ext-vars/build/index")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "expo-gradle-jvmargs": ConfigPluginOptions<typeof import("expo-gradle-jvmargs/plugin/build/withGradleJvmArgs")["default"]>;
    "expo-health-connect": ConfigPluginOptions<typeof import("expo-health-connect/build/withHealthConnect")["default"]>;
    "expo-horizon-core": ConfigPluginOptions<typeof import("expo-horizon-core/plugin/build/withHorizon")["default"]>;
    "expo-horizon-location": ConfigPluginOptions<typeof import("expo-horizon-location/plugin/build/withLocation")["default"]>;
    "expo-horizon-notifications": ConfigPluginOptions<typeof import("expo-horizon-notifications/plugin/build/withNotifications")["default"]>;
    "expo-iap": ConfigPluginOptions<typeof import("expo-iap/plugin/build/withIAP")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "expo-idnow-auto-ident-config-plugin": ConfigPluginOptions<typeof import("expo-idnow-auto-ident-config-plugin/build/withIdNowAutoIdent")["default"]>;
    "expo-ignore-battery-optimizations": ConfigPluginOptions<typeof import("expo-ignore-battery-optimizations/plugin/build/withBatteryOptimizationPermissions")["default"]>;
    "expo-image-picker": ConfigPluginOptions<typeof import("expo-image-picker/plugin/build/withImagePicker")["default"]>;
    "expo-install-apps": ConfigPluginOptions<typeof import("expo-install-apps/plugin/build/withAppList")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "expo-instant-app": ConfigPluginOptions<typeof import("expo-instant-app/plugin/build/lib/withInstantAppManifest")["default"]>;
    "expo-libvlc-player": ConfigPluginOptions<typeof import("expo-libvlc-player/plugin/build/withExpoLibVlcPlayer")["default"]>;
    "expo-linkrunner": ConfigPluginOptions<typeof import("expo-linkrunner/build/module")["default"]>;
    "expo-live-activity": ConfigPluginOptions<typeof import("expo-live-activity/plugin/build/index")["default"]>;
    // This Packages doesn't ship types for config plugin:
    "expo-live-updates": ConfigPluginOptions<unknown>;
    // @ts-expect-error [Invalid types or not exported]
    "expo-llm-mediapipe": ConfigPluginOptions<typeof import("expo-llm-mediapipe/app.plugin")["default"]>;
    "expo-local-authentication": ConfigPluginOptions<typeof import("expo-local-authentication/plugin/build/withLocalAuthentication")["default"]>;
    "expo-localization": ConfigPluginOptions<typeof import("expo-localization/plugin/build/withExpoLocalization")["default"]>;
    "expo-location": ConfigPluginOptions<typeof import("expo-location/plugin/build/withLocation")["default"]>;
    "expo-mail-composer": ConfigPluginOptions<typeof import("expo-mail-composer/plugin/build/withMailComposer")["default"]>;
    // This Packages doesn't ship types for config plugin:
    "expo-mapbox-navigation": ConfigPluginOptions<unknown>;
    "expo-maps": ConfigPluginOptions<typeof import("expo-maps/plugin/build/withMapsLocation")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "expo-mds": ConfigPluginOptions<typeof import("expo-mds/app.plugin")["default"]>;
    "expo-media-library": ConfigPluginOptions<typeof import("expo-media-library/plugin/build/withMediaLibrary")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "expo-motion-detector": ConfigPluginOptions<typeof import("expo-motion-detector/app.plugin")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "expo-moyasar-apple-pay": ConfigPluginOptions<typeof import("expo-moyasar-apple-pay/app.plugin")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "expo-music-picker": ConfigPluginOptions<typeof import("expo-music-picker/app.plugin")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "expo-native-alipay": ConfigPluginOptions<typeof import("expo-native-alipay/app.plugin")["default"]>;
    "expo-native-asset": ConfigPluginOptions<typeof import("expo-native-asset/build/index")["default"]>;
    "expo-native-lockfiles": ConfigPluginOptions<typeof import("expo-native-lockfiles/plugin/build/lockfile-plugin")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "expo-native-wechat": ConfigPluginOptions<typeof import("expo-native-wechat/app.plugin")["default"]>;
    "expo-navigation-bar": ConfigPluginOptions<typeof import("expo-navigation-bar/plugin/build/withNavigationBar")["default"]>;
    "expo-notifications": ConfigPluginOptions<typeof import("expo-notifications/plugin/build/withNotifications")["default"]>;
    "expo-payments-stripe": ConfigPluginOptions<typeof import("expo-payments-stripe/plugin/build/withStripe")["default"]>;
    "expo-pip": ConfigPluginOptions<typeof import("expo-pip/plugin/build/index")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "expo-pod-pinner": ConfigPluginOptions<typeof import("expo-pod-pinner/build/plugin/withPodPinner")["default"]>;
    "expo-privacy-manifest-polyfill-plugin": ConfigPluginOptions<typeof import("expo-privacy-manifest-polyfill-plugin/build/withExpoPrivacyManifestPolyfillPlugin")["default"]>;
    "expo-quest-notifications": ConfigPluginOptions<typeof import("expo-quest-notifications/plugin/build/withNotifications")["default"]>;
    // @ts-expect-error [Package uses `exports` in `package.json`, which breaks this import]
    "expo-quick-actions": ConfigPluginOptions<typeof import("expo-quick-actions/plugin/build/index")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "expo-react-native-freshchat": ConfigPluginOptions<typeof import("expo-react-native-freshchat/app.plugin")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "expo-release-signing": ConfigPluginOptions<typeof import("expo-release-signing/dist/index")["default"]>;
    "expo-request-more-ram": ConfigPluginOptions<typeof import("expo-request-more-ram/build/index")["default"]>;
    "expo-required-hardware": ConfigPluginOptions<typeof import("expo-required-hardware/build/withRequiredHardware")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "expo-roomplan": ConfigPluginOptions<typeof import("expo-roomplan/app.plugin")["default"]>;
    "expo-router": ConfigPluginOptions<typeof import("expo-router/plugin/build/index")["default"]>;
    // @ts-expect-error [Package uses `exports` in `package.json`, which breaks this import]
    "expo-safari-web-extension": ConfigPluginOptions<typeof import("expo-safari-web-extension/lib/typescript/module/src/index")["default"]>;
    "expo-screen-orientation": ConfigPluginOptions<typeof import("expo-screen-orientation/plugin/build/withScreenOrientation")["default"]>;
    "expo-secure-store": ConfigPluginOptions<typeof import("expo-secure-store/plugin/build/withSecureStore")["default"]>;
    "expo-sensors": ConfigPluginOptions<typeof import("expo-sensors/plugin/build/withSensors")["default"]>;
    "expo-share-extension": ConfigPluginOptions<typeof import("expo-share-extension/plugin/build/index")["default"]>;
    "expo-share-intent": ConfigPluginOptions<typeof import("expo-share-intent/plugin/build/index")["default"]>;
    "expo-shazamkit": ConfigPluginOptions<typeof import("expo-shazamkit/plugin/build/withShazamKit")["default"]>;
    "expo-signature": ConfigPluginOptions<typeof import("expo-signature/plugin/build/withLocalAuthentication")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "expo-speech-recognition": ConfigPluginOptions<typeof import("expo-speech-recognition/app.plugin")["default"]>;
    "expo-splash-screen": ConfigPluginOptions<typeof import("expo-splash-screen/plugin/build/withSplashScreen")["default"]>;
    // @ts-expect-error [Package uses `exports` in `package.json`, which breaks this import]
    "expo-sqlite": ConfigPluginOptions<typeof import("expo-sqlite/plugin/build/withSQLite")["default"]>;
    "expo-stores-games-services": ConfigPluginOptions<typeof import("expo-stores-games-services/plugin/build/index")["default"]>;
    "expo-stt": ConfigPluginOptions<typeof import("expo-stt/plugin/build/withSpeechRecognition")["default"]>;
    // @ts-expect-error [Package uses `exports` in `package.json`, which breaks this import]
    "expo-superwall": ConfigPluginOptions<typeof import("expo-superwall/plugin/build/index")["default"]>;
    "expo-system-ui": ConfigPluginOptions<typeof import("expo-system-ui/plugin/build/withSystemUI")["default"]>;
    "expo-tappay-line-pay": ConfigPluginOptions<typeof import("expo-tappay-line-pay/plugin/build/index")["default"]>;
    "expo-task-manager": ConfigPluginOptions<typeof import("expo-task-manager/plugin/build/withTaskManager")["default"]>;
    // This Packages doesn't ship types for config plugin:
    "expo-tiktok-sdk": ConfigPluginOptions<unknown>;
    "expo-tracking-transparency": ConfigPluginOptions<typeof import("expo-tracking-transparency/plugin/build/withTrackingTransparency")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "expo-umeng": ConfigPluginOptions<typeof import("expo-umeng/app.plugin")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "expo-umeng-analytics": ConfigPluginOptions<typeof import("expo-umeng-analytics/app.plugin")["default"]>;
    "expo-updates": ConfigPluginOptions<typeof import("expo-updates/plugin/build/withUpdates")["default"]>;
    "expo-user-identity": ConfigPluginOptions<typeof import("expo-user-identity/plugin/build/index")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "expo-vas-lib": ConfigPluginOptions<typeof import("expo-vas-lib/app.plugin")["default"]>;
    "expo-video": ConfigPluginOptions<typeof import("expo-video/plugin/build/withExpoVideo")["default"]>;
    // This Packages doesn't ship types for config plugin:
    "expo-video-composer": ConfigPluginOptions<unknown>;
    "expo-vision-image-scanner": ConfigPluginOptions<typeof import("expo-vision-image-scanner/plugin/build/index")["default"]>;
    "expo-web-browser": ConfigPluginOptions<typeof import("expo-web-browser/plugin/build/withWebBrowser")["default"]>;
    "expo-wechat": ConfigPluginOptions<typeof import("expo-wechat/plugin/build/index")["default"]>;
    "expo-whisper": ConfigPluginOptions<typeof import("expo-whisper/plugin/src/index")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "expo-wireguard": ConfigPluginOptions<typeof import("expo-wireguard/app.plugin")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "expo-zendesk-messaging": ConfigPluginOptions<typeof import("expo-zendesk-messaging/plugin/index")["default"]>;
    "ez-expo-share": ConfigPluginOptions<typeof import("ez-expo-share/plugin/build/withShareExtension")["default"]>;
    "ez-zendesk-unified-sdk": ConfigPluginOptions<typeof import("ez-zendesk-unified-sdk/plugin/build/index")["default"]>;
    "fork-expo-document-picker": ConfigPluginOptions<typeof import("fork-expo-document-picker/plugin/build/withDocumentPicker")["default"]>;
    "freerasp-react-native": ConfigPluginOptions<typeof import("freerasp-react-native/plugin/build/index")["default"]>;
    "hypertrack-sdk-expo": ConfigPluginOptions<typeof import("hypertrack-sdk-expo/build/index")["default"]>;
    "instabug-reactnative": ConfigPluginOptions<typeof import("instabug-reactnative/plugin/src/index")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "jpush-expo-config-plugin": ConfigPluginOptions<typeof import("jpush-expo-config-plugin/app.plugin")["default"]>;
    "karte-expo-plugin": ConfigPluginOptions<typeof import("karte-expo-plugin/build/withKarte")["default"]>;
    // This Packages doesn't ship types for config plugin:
    lama: ConfigPluginOptions<unknown>;
    "letro-passport": ConfigPluginOptions<typeof import("letro-passport/plugin/build/index")["default"]>;
    "llama.rn": ConfigPluginOptions<typeof import("llama.rn/lib/typescript/expo-plugin/withLlamaRN")["default"]>;
    // @ts-expect-error [Package uses `exports` in `package.json`, which breaks this import]
    "mindbox-expo-plugin": ConfigPluginOptions<typeof import("mindbox-expo-plugin/build/withMindbox")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "mx-jpush-expo": ConfigPluginOptions<typeof import("mx-jpush-expo/app.plugin")["default"]>;
    "newrelic-react-native-agent": ConfigPluginOptions<typeof import("newrelic-react-native-agent/plugin/build/index")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "onesignal-expo-plugin": ConfigPluginOptions<typeof import("onesignal-expo-plugin/build/onesignal/withOneSignal")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "onnxruntime-react-native": ConfigPluginOptions<typeof import("onnxruntime-react-native/app.plugin")["default"]>;
    "patch-project": ConfigPluginOptions<typeof import("patch-project/build/withPatchPlugin")["default"]>;
    "pushwoosh-expo-plugin": ConfigPluginOptions<typeof import("pushwoosh-expo-plugin/plugin/build/withPushwoosh")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "pushy-expo-plugin": ConfigPluginOptions<typeof import("pushy-expo-plugin/app.plugin")["default"]>;
    "react-native-add-calendar-event": ConfigPluginOptions<typeof import("react-native-add-calendar-event/plugin/build/withAddCalendarEvent")["default"]>;
    "react-native-admob-native-ads": ConfigPluginOptions<typeof import("react-native-admob-native-ads/plugin/build/withAdmobNativeAds")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "react-native-altitude-plugin": ConfigPluginOptions<typeof import("react-native-altitude-plugin/plugin/src/withAltitude")["default"]>;
    "react-native-app-auth": ConfigPluginOptions<typeof import("react-native-app-auth/plugin/build/index")["default"]>;
    "react-native-app-clip": ConfigPluginOptions<typeof import("react-native-app-clip/plugin/build/index")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "react-native-appsflyer": ConfigPluginOptions<typeof import("react-native-appsflyer/expo/withAppsFlyer")["default"]>;
    // @ts-expect-error [Package uses `exports` in `package.json`, which breaks this import]
    "react-native-attribution-token": ConfigPluginOptions<typeof import("react-native-attribution-token/lib/typescript/expo-plugin/withBoringSSLFix")["default"]>;
    "react-native-audio-api": ConfigPluginOptions<typeof import("react-native-audio-api/lib/typescript/plugin/withAudioAPI")["default"]>;
    "react-native-auth0": ConfigPluginOptions<typeof import("react-native-auth0/src/plugin/withAuth0")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "react-native-auto-skeleton": ConfigPluginOptions<typeof import("react-native-auto-skeleton/src/expo-plugins/withAutoSkeleton")["default"]>;
    "react-native-background-fetch": ConfigPluginOptions<typeof import("react-native-background-fetch/expo/plugin/build/index")["default"]>;
    "react-native-background-geolocation": ConfigPluginOptions<typeof import("react-native-background-geolocation/expo/plugin/build/index")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "react-native-blasted-image": ConfigPluginOptions<typeof import("react-native-blasted-image/blastedAssets")["default"]>;
    "react-native-ble-manager": ConfigPluginOptions<typeof import("react-native-ble-manager/plugin/build/withBLE")["default"]>;
    "react-native-ble-plx": ConfigPluginOptions<typeof import("react-native-ble-plx/plugin/build/withBLE")["default"]>;
    "react-native-bootsplash": ConfigPluginOptions<typeof import("react-native-bootsplash/dist/typescript/expo")["withBootSplash"]>;
    // @ts-expect-error [Package uses `exports` in `package.json`, which breaks this import]
    "react-native-bottom-tabs": ConfigPluginOptions<typeof import("react-native-bottom-tabs/lib/typescript/src/expo")["default"]>;
    // This Packages doesn't ship types for config plugin:
    "react-native-call-detection": ConfigPluginOptions<unknown>;
    // @ts-expect-error [Invalid types or not exported]
    "react-native-candle": ConfigPluginOptions<typeof import("react-native-candle/plugin/withIosDeploymentTarget")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "react-native-capture-protection": ConfigPluginOptions<typeof import("react-native-capture-protection/plugins/withPlugin")["default"]>;
    "react-native-cloud-storage": ConfigPluginOptions<typeof import("react-native-cloud-storage/dist/typescript/expo-plugin/index")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "react-native-cloud-store": ConfigPluginOptions<typeof import("react-native-cloud-store/plugins/withCloud")["default"]>;
    "react-native-compressor": ConfigPluginOptions<typeof import("react-native-compressor/lib/typescript/expo-plugin/compressor")["default"]>;
    "react-native-core-bluetooth": ConfigPluginOptions<typeof import("react-native-core-bluetooth/lib/typescript/src/expo-plugin/withCoreBluetooth")["default"]>;
    // @ts-expect-error [Package uses `exports` in `package.json`, which breaks this import]
    "react-native-credentials-manager": ConfigPluginOptions<typeof import("react-native-credentials-manager/app.plugin")["default"]>;
    "react-native-crisp-chat-sdk": ConfigPluginOptions<typeof import("react-native-crisp-chat-sdk/plugin/build/withCrispChat")["default"]>;
    // @ts-expect-error [Package uses `exports` in `package.json`, which breaks this import]
    "react-native-deepgram": ConfigPluginOptions<typeof import("react-native-deepgram/plugin/build/index")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "react-native-device-activity": ConfigPluginOptions<typeof import("react-native-device-activity/app.plugin")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "react-native-dji-mobile-sdk": ConfigPluginOptions<typeof import("react-native-dji-mobile-sdk/app.plugin")["default"]>;
    // @ts-expect-error [Package uses `exports` in `package.json`, which breaks this import]
    "react-native-document-scanner-plugin": ConfigPluginOptions<typeof import("react-native-document-scanner-plugin/expo-plugin/build/withDocumentScanner")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "react-native-dynamic-activities": ConfigPluginOptions<typeof import("react-native-dynamic-activities/app.plugin")["default"]>;
    "react-native-edge-to-edge": ConfigPluginOptions<typeof import("react-native-edge-to-edge/dist/typescript/expo")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "react-native-email-link": ConfigPluginOptions<typeof import("react-native-email-link/plugin/withEmailLink")["default"]>;
    // @ts-expect-error [Package uses `exports` in `package.json`, which breaks this import]
    "react-native-embedded-httpd": ConfigPluginOptions<typeof import("react-native-embedded-httpd/lib/typescript/module/withoutNettyMeta")["default"]>;
    // @ts-expect-error [Package uses `exports` in `package.json`, which breaks this import]
    "react-native-epson-escposprinter": ConfigPluginOptions<typeof import("react-native-epson-escposprinter/lib/typescript/module/withPluginConfigs")["default"]>;
    "react-native-expo-braintree": ConfigPluginOptions<typeof import("react-native-expo-braintree/lib/typescript/src/plugin/withExpoBraintree")["default"]>;
    "react-native-expo-metamap-sdk": ConfigPluginOptions<typeof import("react-native-expo-metamap-sdk/plugin/build/index")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "react-native-expo-moengage": ConfigPluginOptions<typeof import("react-native-expo-moengage/build/index")["default"]>;
    "react-native-face-detector-camera": ConfigPluginOptions<typeof import("react-native-face-detector-camera/plugin/build/withCamera")["default"]>;
    "react-native-fast-tflite": ConfigPluginOptions<typeof import("react-native-fast-tflite/lib/typescript/src/expo-plugin/withFastTFLite")["default"]>;
    "react-native-fbads": ConfigPluginOptions<typeof import("react-native-fbads/plugin/build/withReactNativeFbads")["default"]>;
    "react-native-fbsdk-next": ConfigPluginOptions<typeof import("react-native-fbsdk-next/plugin/build/withFacebook")["default"]>;
    // @ts-expect-error [Package uses `exports` in `package.json`, which breaks this import]
    "react-native-file-viewer-turbo": ConfigPluginOptions<typeof import("react-native-file-viewer-turbo/lib/typescript/module/src/plugin/withFilePreviewTurbo")["default"]>;
    "react-native-flipper-performance-plugin": ConfigPluginOptions<typeof import("react-native-flipper-performance-plugin/plugin/build/index")["default"]>;
    "react-native-full-screen-notification-incoming-call": ConfigPluginOptions<typeof import("react-native-full-screen-notification-incoming-call/lib/typescript/src/expo")["default"]>;
    // This Packages doesn't ship types for config plugin:
    "react-native-game-kit": ConfigPluginOptions<unknown>;
    // This Packages doesn't ship types for config plugin:
    "react-native-get-music-files": ConfigPluginOptions<unknown>;
    "react-native-gifsicle": ConfigPluginOptions<typeof import("react-native-gifsicle/lib/typescript/src/expo-plugin/gifsicle")["default"]>;
    // @ts-expect-error [Package uses `exports` in `package.json`, which breaks this import]
    "react-native-google-auth": ConfigPluginOptions<typeof import("react-native-google-auth/plugin/build/withGoogleAuth")["default"]>;
    "react-native-google-cast": ConfigPluginOptions<typeof import("react-native-google-cast/lib/typescript/plugin/withGoogleCast")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "react-native-google-fit": ConfigPluginOptions<typeof import("react-native-google-fit/app.plugin")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "react-native-google-maps-plus": ConfigPluginOptions<typeof import("react-native-google-maps-plus/expoConfig/build/index")["default"]>;
    "react-native-google-mobile-ads": ConfigPluginOptions<typeof import("react-native-google-mobile-ads/plugin/build/index")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "react-native-health": ConfigPluginOptions<typeof import("react-native-health/app.plugin")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "react-native-health-connect": ConfigPluginOptions<typeof import("react-native-health-connect/app.plugin")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "react-native-helios": ConfigPluginOptions<typeof import("react-native-helios/app.plugin")["default"]>;
    // @ts-expect-error [Package uses `exports` in `package.json`, which breaks this import]
    "react-native-iap": ConfigPluginOptions<typeof import("react-native-iap/plugin/build/withIAP")["default"]>;
    "react-native-icon-converter": ConfigPluginOptions<typeof import("react-native-icon-converter/lib/typescript/module/withIcons")["default"]>;
    "react-native-image-marker": ConfigPluginOptions<typeof import("react-native-image-marker/lib/typescript/expo-plugin/withImageMarker")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "react-native-image-sequence-encoder": ConfigPluginOptions<typeof import("react-native-image-sequence-encoder/plugin/withImageSeqEncoder")["default"]>;
    "react-native-intercom-expo-config-plugin": ConfigPluginOptions<typeof import("react-native-intercom-expo-config-plugin/build/withIntercom")["default"]>;
    "react-native-keyevent-expo-config-plugin": ConfigPluginOptions<typeof import("react-native-keyevent-expo-config-plugin/build/withReactNativeKeyevent")["default"]>;
    "react-native-keys": ConfigPluginOptions<typeof import("react-native-keys/lib/typescript/plugin/src/index")["default"]>;
    "react-native-legal": ConfigPluginOptions<typeof import("react-native-legal/plugin/build/index")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "react-native-libsodium": ConfigPluginOptions<typeof import("react-native-libsodium/app.plugin")["default"]>;
    "react-native-localization-settings": ConfigPluginOptions<typeof import("react-native-localization-settings/plugin/build/index")["default"]>;
    "react-native-localize": ConfigPluginOptions<typeof import("react-native-localize/dist/typescript/expo")["default"]>;
    "react-native-localize-date": ConfigPluginOptions<typeof import("react-native-localize-date/plugin/build/withLocalizations")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "react-native-map-link": ConfigPluginOptions<typeof import("react-native-map-link/app.plugin")["default"]>;
    "react-native-mapbox-turn-by-turn-navigation": ConfigPluginOptions<typeof import("react-native-mapbox-turn-by-turn-navigation/lib/typescript/src/plugin/withMapbox")["default"]>;
    "react-native-maps": ConfigPluginOptions<typeof import("react-native-maps/dist/plugin/src/index")["default"]>;
    "react-native-metamap-sdk": ConfigPluginOptions<typeof import("react-native-metamap-sdk/plugin/build/index")["default"]>;
    // This Packages doesn't ship types for config plugin:
    "react-native-mlx": ConfigPluginOptions<unknown>;
    // @ts-expect-error [Invalid types or not exported]
    "react-native-moyasar-apple-pay": ConfigPluginOptions<typeof import("react-native-moyasar-apple-pay/app.plugin")["default"]>;
    "react-native-msal": ConfigPluginOptions<typeof import("react-native-msal/plugin/build/withReactNativeMSAL")["default"]>;
    // This Packages doesn't ship types for config plugin:
    "react-native-multipeer": ConfigPluginOptions<unknown>;
    // @ts-expect-error [Package uses `exports` in `package.json`, which breaks this import]
    "react-native-nai-timer": ConfigPluginOptions<typeof import("react-native-nai-timer/plugin/build/withNaiTimer")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "react-native-navigation-mode": ConfigPluginOptions<typeof import("react-native-navigation-mode/app.plugin")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "react-native-nfc-manager": ConfigPluginOptions<typeof import("react-native-nfc-manager/app.plugin")["default"]>;
    "react-native-nitro-inspire-face": ConfigPluginOptions<typeof import("react-native-nitro-inspire-face/lib/typescript/module/src/expo-plugin/withInspireFace")["default"]>;
    "react-native-nitro-readium": ConfigPluginOptions<typeof import("react-native-nitro-readium/plugins/build/index")["default"]>;
    "react-native-nitro-screen-recorder": ConfigPluginOptions<typeof import("react-native-nitro-screen-recorder/lib/typescript/expo-plugin/withScreenRecorder")["default"]>;
    // @ts-expect-error [Package uses `exports` in `package.json`, which breaks this import]
    "react-native-nitro-sound": ConfigPluginOptions<typeof import("react-native-nitro-sound/lib/typescript/plugin/src/index")["default"]>;
    // @ts-expect-error [Package uses `exports` in `package.json`, which breaks this import]
    "react-native-nitro-speech-recognition": ConfigPluginOptions<typeof import("react-native-nitro-speech-recognition/plugin/build/withNitroSpeechRecognition")["default"]>;
    "react-native-notificare": ConfigPluginOptions<typeof import("react-native-notificare/lib/plugin/withNotificare")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "react-native-notificare-geo": ConfigPluginOptions<typeof import("react-native-notificare-geo/lib/plugin/withNotificareGeo")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "react-native-notificare-push": ConfigPluginOptions<typeof import("react-native-notificare-push/lib/plugin/withNotificarePush")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "react-native-notificare-push-ui": ConfigPluginOptions<typeof import("react-native-notificare-push-ui/lib/plugin/withNotificarePushUI")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "react-native-notificare-scannables": ConfigPluginOptions<typeof import("react-native-notificare-scannables/lib/plugin/withNotificareScannables")["default"]>;
    // @ts-expect-error [Package uses `exports` in `package.json`, which breaks this import]
    "react-native-orientation-director": ConfigPluginOptions<typeof import("react-native-orientation-director/plugin/build/index")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "react-native-ota-hot-update": ConfigPluginOptions<typeof import("react-native-ota-hot-update/plugin/src/index.ts")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "react-native-package-checker": ConfigPluginOptions<typeof import("react-native-package-checker/app.plugin")["default"]>;
    "react-native-permissions": ConfigPluginOptions<typeof import("react-native-permissions/dist/typescript/expo")["default"]>;
    // This Packages doesn't ship types for config plugin:
    "react-native-quick-crypto": ConfigPluginOptions<unknown>;
    "react-native-radar": ConfigPluginOptions<typeof import("react-native-radar/plugin/build/withRadar")["default"]>;
    "react-native-rate-app": ConfigPluginOptions<typeof import("react-native-rate-app/lib/typescript/plugin/withReactNativeRateApp")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "react-native-render-lynx": ConfigPluginOptions<typeof import("react-native-render-lynx/plugin/withRenderLynx")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "react-native-render-swift-ui": ConfigPluginOptions<typeof import("react-native-render-swift-ui/app.plugin")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "react-native-rfid8500-zebra": ConfigPluginOptions<typeof import("react-native-rfid8500-zebra/app.plugin")["default"]>;
    "react-native-safari-extension": ConfigPluginOptions<typeof import("react-native-safari-extension/plugin/build/withSafariExtension")["default"]>;
    // @ts-expect-error [Package uses `exports` in `package.json`, which breaks this import]
    "react-native-safeguard": ConfigPluginOptions<typeof import("react-native-safeguard/withSafeguard")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "react-native-salesforce-chat-sdk": ConfigPluginOptions<typeof import("react-native-salesforce-chat-sdk/plugin/index")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "react-native-savanitdev-thermal-printer": ConfigPluginOptions<typeof import("react-native-savanitdev-thermal-printer/app.plugin")["default"]>;
    // This Packages doesn't ship types for config plugin:
    "react-native-screen-time": ConfigPluginOptions<unknown>;
    "react-native-screenshot-aware": ConfigPluginOptions<typeof import("react-native-screenshot-aware/lib/typescript/plugin/withReactNativeScreenshotAware")["default"]>;
    "react-native-share": ConfigPluginOptions<typeof import("react-native-share/plugin/build/index")["default"]>;
    "react-native-spotlight-search": ConfigPluginOptions<typeof import("react-native-spotlight-search/plugin/build/withSpotlight")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "react-native-ssl-manager": ConfigPluginOptions<typeof import("react-native-ssl-manager/app.plugin")["default"]>;
    // This Packages doesn't ship types for config plugin:
    "react-native-status-keycard": ConfigPluginOptions<unknown>;
    "react-native-stripe-apple-pay": ConfigPluginOptions<typeof import("react-native-stripe-apple-pay/lib/typescript/src/plugins/withStripe")["default"]>;
    // This Packages doesn't ship types for config plugin:
    "react-native-stripe-terminal": ConfigPluginOptions<unknown>;
    "react-native-theoplayer": ConfigPluginOptions<typeof import("react-native-theoplayer/lib/typescript/plugins/expo/withTHEOplayer")["default"]>;
    // @ts-expect-error [Package uses `exports` in `package.json`, which breaks this import]
    "react-native-tiktok": ConfigPluginOptions<typeof import("react-native-tiktok/plugin/build/withTiktok")["default"]>;
    "react-native-twilio-video-webrtc": ConfigPluginOptions<typeof import("react-native-twilio-video-webrtc/plugin/build/index")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "react-native-uaepass": ConfigPluginOptions<typeof import("react-native-uaepass/plugin/index")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "react-native-use-health-kit": ConfigPluginOptions<typeof import("react-native-use-health-kit/app.plugin")["default"]>;
    // This Packages doesn't ship types for config plugin:
    "react-native-use-qili": ConfigPluginOptions<unknown>;
    "react-native-v8": ConfigPluginOptions<typeof import("react-native-v8/plugin/build/withV8ExpoAdapter")["default"]>;
    "react-native-vector-image": ConfigPluginOptions<typeof import("react-native-vector-image/plugin/build/withVectorImage")["default"]>;
    "react-native-video": ConfigPluginOptions<typeof import("react-native-video/lib/expo-plugins/withRNVideo")["default"]>;
    "react-native-vision-camera": ConfigPluginOptions<typeof import("react-native-vision-camera/lib/typescript/expo-plugin/withVisionCamera")["default"]>;
    "react-native-vlc-media-player": ConfigPluginOptions<typeof import("instabug-reactnative/plugin/src/index.ts")["default"]>;
    "react-native-voice-voice-reworked": ConfigPluginOptions<typeof import("react-native-voice-voice-reworked/plugin/build/withVoice")["default"]>;
    "react-native-voicekit": ConfigPluginOptions<typeof import("react-native-voicekit/dist/typescript/expo-plugin/index")["default"]>;
    "react-native-vosk": ConfigPluginOptions<typeof import("react-native-vosk/plugin/build/withVosk")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "react-native-webassembly": ConfigPluginOptions<typeof import("react-native-webassembly/app.plugin")["default"]>;
    // This Packages doesn't ship types for config plugin:
    "react-native-whip-whep": ConfigPluginOptions<unknown>;
    "react-native-wifi-reborn": ConfigPluginOptions<typeof import("react-native-wifi-reborn/plugin/dist/withWifi")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "react-native-yoco": ConfigPluginOptions<typeof import("react-native-yoco/app.plugin")["default"]>;
    "react-viro-sw": ConfigPluginOptions<typeof import("react-viro-sw/dist/plugins/withViro")["default"]>;
    // This Packages doesn't ship types for config plugin:
    "rn-fade-wrapper": ConfigPluginOptions<unknown>;
    // @ts-expect-error [Invalid types or not exported]
    "rn-nomba-terminal-sdk": ConfigPluginOptions<typeof import("rn-nomba-terminal-sdk/app.plugin")["default"]>;
    "rnn-expo-plugin": ConfigPluginOptions<typeof import("rnn-expo-plugin/build/withRNN")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "rns-webview": ConfigPluginOptions<typeof import("rns-webview/app.plugin")["default"]>;
    "sentry-expo": ConfigPluginOptions<typeof import("sentry-expo/plugin/build/withSentry")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "singular-react-native": ConfigPluginOptions<typeof import("singular-react-native/app.plugin")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "singular-react-native-kids-sdk": ConfigPluginOptions<typeof import("singular-react-native-kids-sdk/app.plugin")["default"]>;
    // This Packages doesn't ship types for config plugin:
    "sodium-react-native-direct": ConfigPluginOptions<unknown>;
    "square-expo-plugin": ConfigPluginOptions<typeof import("square-expo-plugin/build/index")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "swiftui-native": ConfigPluginOptions<typeof import("swiftui-native/app.plugin")["default"]>;
    test12321test: ConfigPluginOptions<typeof import("test12321test/plugin/build/index")["default"]>;
    "testflight-dev-deploy": ConfigPluginOptions<typeof import("testflight-dev-deploy/build/index")["default"]>;
    // This Packages doesn't ship types for config plugin:
    tracker: ConfigPluginOptions<unknown>;
    // This Packages doesn't ship types for config plugin:
    unitest: ConfigPluginOptions<unknown>;
    "vibes-react-native-expo": ConfigPluginOptions<typeof import("vibes-react-native-expo/plugin/build/index")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "webengage-expo-push": ConfigPluginOptions<typeof import("webengage-expo-push/build/webengage/withWebEngage")["default"]>;
    "widget-watchos-expo-plugin": ConfigPluginOptions<typeof import("widget-watchos-expo-plugin/plugin/build/index")["default"]>;
    "with-react-native-tcp-socket": ConfigPluginOptions<typeof import("with-react-native-tcp-socket/build/withReactNativeTcpSocket")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "with-rn-bluetooth-classic": ConfigPluginOptions<typeof import("with-rn-bluetooth-classic/plugin/lib/index")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "with-rn-contacts": ConfigPluginOptions<typeof import("with-rn-contacts/build/src/index")["default"]>;
    // @ts-expect-error [Invalid types or not exported]
    "with-rn-image-crop-picker": ConfigPluginOptions<typeof import("with-rn-image-crop-picker/build/src/index")["default"]>;

    /* Errors:
[
  [
    "Package uses `exports` in `package.json`, which breaks this import",
    [
      "@b8safe/react-native-safe",
      "@calljmp/react-native",
      "@dbkable/react-native-speech-to-text",
      "@deeplinknow/react-native",
      "@fingerprintjs/fingerprintjs-pro-react-native",
      "@grupalia/react-native-photo-picker",
      "@honeycombio/opentelemetry-react-native",
      "@hot-updater/react-native",
      "@huymobile/react-native-sms-retriever-nitro-module",
      "@intercom/intercom-react-native",
      "@kingstinct/react-native-healthkit",
      "@lightbase/rn-design-system",
      "@maplibre/maplibre-react-native",
      "@mj-studio/react-native-naver-map",
      "@naveen521kk/react-native-tokenizer",
      "@novastera-oss/rn-google-signin",
      "@oleg_svetlichnyi/expo-icloud-storage",
      "@opacity-labs/react-native-opacity",
      "@portone/react-native-sdk",
      "@react-native-google-signin/google-signin",
      "@reclaimprotocol/inapp-rn-sdk",
      "@rnmapbox/maps",
      "@track-asia/trackasia-react-native",
      "@vietmap/vietmap-gl-react-native",
      "expo-asset",
      "expo-clear-keychain",
      "expo-font",
      "expo-quick-actions",
      "expo-safari-web-extension",
      "expo-sqlite",
      "expo-superwall",
      "mindbox-expo-plugin",
      "react-native-attribution-token",
      "react-native-bottom-tabs",
      "react-native-credentials-manager",
      "react-native-deepgram",
      "react-native-document-scanner-plugin",
      "react-native-embedded-httpd",
      "react-native-epson-escposprinter",
      "react-native-file-viewer-turbo",
      "react-native-google-auth",
      "react-native-iap",
      "react-native-nai-timer",
      "react-native-nitro-sound",
      "react-native-nitro-speech-recognition",
      "react-native-orientation-director",
      "react-native-safeguard",
      "react-native-tiktok"
    ]
  ],
  [
    "Redundant ignore override",
    [
      "@daily-co/config-plugin-rn-daily-js",
      "@mikekhristo/expo-tiktok-opensdk",
      "@spreen/ffmpeg-kit-react-native-config",
      "expo-gradle-jvmargs",
      "expo-idnow-auto-ident-config-plugin",
      "react-native-ota-hot-update",
      "with-rn-bluetooth-classic"
    ]
  ],
  [
    "Package doesn't ship an app.plugin.js file",
    [
      "@datadog/mobile-react-native",
      "@fleetbase/react-native-mapbox-navigation",
      "@sparkfabrik/react-native-idfa-aaid",
      "@tripleplaypay/react-native",
      "@yownes/core",
      "customerapp",
      "eos",
      "expo-custom-android-styles-plugin",
      "expo-dev-launcher",
      "expo-live-updates",
      "expo-mapbox-navigation",
      "expo-tiktok-sdk",
      "expo-video-composer",
      "lama",
      "react-native-call-detection",
      "react-native-game-kit",
      "react-native-get-music-files",
      "react-native-mlx",
      "react-native-multipeer",
      "react-native-quick-crypto",
      "react-native-screen-time",
      "react-native-status-keycard",
      "react-native-stripe-terminal",
      "react-native-use-qili",
      "react-native-whip-whep",
      "rn-fade-wrapper",
      "sodium-react-native-direct",
      "tracker",
      "unitest"
    ]
  ]
]
    */
}
