name: Auto Update Plugins

on:
  schedule:
    - cron: '0 6 * * 6' # Every Saturday at 06:00 UTC
  workflow_dispatch: # Allows manual trigger

jobs:
  update:
    runs-on: ubuntu-latest
    # Give it a bit more time, especially if updates can be extensive or Bun is slow sometimes.
    timeout-minutes: 5

    permissions:
      contents: write # Needed for checkout and creating a commit
      pull-requests: write # Needed for creating a pull request

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # We need to fetch all branches for creating a new branch
          persist-credentials: false # Uses the token provided by the 'permissions' block

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "latest"

      - name: Install dependencies
        run: bun install --filter './'

      - name: Run update script
        run: bun run update
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore(plugins): Automated update of config plugins"
          title: "chore(plugins): Automated update of config plugins"
          body: |
            This PR updates the list of config plugins automatically.

            **Changes include:**
            - Updates to plugin configurations
            - Any new plugins discovered
            - (Possible manual cleanup may be required for breaking changes or conflicts)

            Please review the changes carefully.
          branch: "auto-update-plugins"
          base: main
          labels: |
            automated
            config-plugins