name: Auto Update

on:
  schedule:
    - cron: '0 6 * * 6' # Every Saturday at 06:00 UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "latest"

      - name: Install dependencies
        run: bun install

      - name: Run update script
        run: bun run update
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PLEASE_GH_TOKEN }}

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PLEASE_GH_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "chore: automated weekly update"
            git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
            git push
          fi
