name: Auto Update

on:
  schedule:
    - cron: '0 6 * * 6' # Every Saturday at 06:00 UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4
        with:
          # We need to fetch all branches for creating a new branch
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "latest"

      - name: Install dependencies
        run: bun install --filter './'

      - name: Run update script
        run: bun run update
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PLEASE_GH_TOKEN }}

      - name: Open Pull Request

        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.RELEASE_PLEASE_GH_TOKEN }}
          "commit-message": "chore: automated update of config plugins"
          title: "chore: Automated update of config plugins"
          body: "This PR updates the list of config plugins automatically. (Might need manual cleanup)"
          branch: "auto-update-plugins"
          base: main
          labels: automated
